training_pipeline_config:
  pipeline_name: Artifact
  artifact_dir: artifact


# artifact/data_ingestion/raw_data & ingested_Data/ Train & Test
data_ingestion_config:
  data_base: machine_learning
  collection_name: DATASET
  data_ingestion: data_ingestion
  raw_data_dir: raw_data
  ingested_dir: ingested_Data
  ingested_train_dir: Train
  ingested_test_dir: Test


# ********************Data Ingestion completed************************

# ********************Data Transformation started*********************

# data_transformation / transformed_data / train & test
data_transformation_config:
  data_transformation_dir: data_transformation
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  processing_dir: processed
  preprocessed_object_file_name: processed.pkl
  feature_eng_file: feature_eng.pkl