
# ********************Data Transformation started*********************

target_column:
  - Cost

numerical_columns:
  - Artist_Reputation
  - Height
  - Weight
  - Width
  - Price_Of_Sculpture
  - Base_Shipping_Price

categorical_columns:
  - Customer_Id
  - Artist_Name
  - Customer_Information
  - Customer_Location
  - Delivery_Date
  - Express_Shipment
  - Fragile
  - Installation_Included
  - International
  - Material
  - Remote_Location
  - Scheduled_Date
  - Transport

outliers_columns:
  - Height 
  - Weight
  - Width
  - Price_Of_Sculpture
  - Cost


drop_columns:
  - Artist_Name
  - Transport
  - Customer_Location
  - Delivery_Date
  - Customer_Id
  - Scheduled_Date

scaling_columns:
  - Artist_Reputation
  - Height
  - Weight
  - Width
  - Price_Of_Sculpture
  - Base_Shipping_Price
  - Cost

